language: cpp
compiler: gcc
matrix:
  include:
      - os: linux
      - addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
            - george-edison55-precise-backports
          packages:
            - g++-7
            - cmake-data
            - cmake
      - env:
        - MATRIX_EVAL="CC=gcc-7 && CXX=g++-7"
before_install:
  - eval "${MATRIX_EVAL}"
script: ./build.sh
addons:
  apt:
    packages:
    - g++ 
    - gdb 
    - libsdl2-dev 
    - zlib1g-dev 
    - liblua5.3 
    - libxdo-dev 
    - patchelf
    - libsdl2-image-dev
  artifacts:
    debug: true
    paths:
    - $(ls *.so)
