#!/bin/bash
# Starts a GDB session on CSGO, injects cheat if it is not already present.
# Send SIGINT to CSGO with: "kill -2 $(pidof csgo_linux64)"


csgo_pid=$(pidof csgo_linux64)
if [ -z "$csgo_pid" ]; then
    /bin/echo -e "\e[31mCS:GO needs to be open before you can inject...\e[0m"
    exit 1
fi

# pBypass for crash dumps being sent
# You may also want to consider using -nobreakpad in your launch options.
sudo rm -rf /tmp/dumps # Remove if it exists
sudo mkdir /tmp/dumps # Make it as root
sudo chmod 000 /tmp/dumps # No permissions

#https://www.kernel.org/doc/Documentation/security/Yama.txt
sudo echo "2" | sudo tee /proc/sys/kernel/yama/ptrace_scope # Only allows root to inject code. This is temp until reboot.

#dlopen method Credits: Aixxe @ aixxe.net
if grep -q Spartan.so /proc/"$csgo_pid"/maps; then
    (sudo echo -e "continue\n"; cat) | sudo gdb -p $csgo_pid
else
    echo "Injecting Spartan debug"
    (sudo echo -e "set \$dlopen = (void*(*)(char*, int)) dlopen\ncall \$dlopen(\"$(pwd)/Spartan.so\", 1)\ncontinue\n"; cat) | sudo gdb -p $csgo_pid
fi
