#!/bin/sh

csgo_pid=$(pidof csgo_linux64)
if [ -z "$csgo_pid" ]; then
    /bin/echo -e "\e[31mCSGO needs to be open before you can inject...\e[0m"
    exit 1
fi



# pBypass for crash dumps being sent
sudo rm -rf /tmp/dumps # Remove if it's there
sudo mkdir /tmp/dumps # Make it as root
sudo chmod 000 /tmp/dumps # No permissions



filename=$(cat build_id)

#Credit: Aixxe @ aixxe.net
if grep -q Spartan.so /proc/$csgo_pid/maps; then
    /bin/echo -e "\e[33mSpartan is already injected... Aborting...\e[0m"
    exit
fi

input="$(
sudo gdb -n -q -batch \
  -ex "attach $csgo_pid" \
  -ex "set \$dlopen = (void*(*)(char*, int)) dlopen" \
  -ex "call \$dlopen(\"$(pwd)/Spartan.so\", 1)" \
  -ex "detach" \
  -ex "quit"
)"



if [ "$last_line" != "\$1 = (void *) 0x0" ]; then
    /bin/echo -e "\e[32mProject Spartan was successfully injected!\e[0m"
else
    /bin/echo -e "\e[31mInjection failed, make sure you've compiled...\e[0m"
fi
